# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://www.{default}/":
  type: upstream
  upstream: "3-hashtag-website:http"

"https://{default}/":
  type: upstream
  upstream: "3-hashtag-website:http"

"http://www.{default}/":
  type: redirect
  to: "https://www.{default}/"

"http://{default}/":
  type: redirect
  to: "https://www.{default}/"

"https://docs.{default}/":
  type: upstream
  upstream: "1-hashtag-docs:http"

"https://app.{default}/":
  type: upstream
  upstream: "2-hashtag-dapp:http"

"https://api.{default}/":
  type: upstream
  upstream: "hashtag-api"
#http://{default}/:
#  cache:
#    cookies:
#    - '*'
#    default_ttl: 0
#    enabled: true
##    headers:
 #   - Accept
 #   - Accept-Language
 # ssi:
 #   enabled: false
 # type: upstream
 # upstream: ui:http
