# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://www.{default}/":
  type: upstream
  upstream: "hashtag-website:http"
  id: "hashtag-web"

"https://{default}/":
  type: upstream
  upstream: "hashtag-website:http"

"http://www.{default}/":
  type: redirect
  to: "https://www.{default}/"

"http://{default}/":
  type: redirect
  to: "https://www.{default}/"

"https://docs.{default}/":
  type: upstream
  upstream: "hashtag-docs:http"
  id: "hashtag-docs"

"https://app.{default}/":
  type: upstream
  upstream: "hashtag-dapp:http"
  id: "hashtag-dapp"

# Hashtag API
"https://api.hashtag-protocol.io/":
  type: upstream
  upstream: "hashtag-api:http"
  id: "hashtag-api"

"http://api.hashtag-protocol.io/":
  type: redirect
  to: "https://api.hashtag-protocol.io/"

"http://hashtag-protocol.io/":
  type: redirect
  to: "https://api.hashtag-protocol.io/"

"https://hashtag-protocol.io/":
  type: redirect
  to: "https://api.hashtag-protocol.io/"
#http://{default}/:
#  cache:
#    cookies:
#    - '*'
#    default_ttl: 0
#    enabled: true
##    headers:
#   - Accept
#   - Accept-Language
# ssi:
#   enabled: false
# type: upstream
# upstream: ui:http
